/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   enum_keys.h                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: psalame <psalame@student.42angouleme.fr    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/04/05 18:43:55 by psalame           #+#    #+#             */
/*   Updated: 2024/04/05 19:07:10 by psalame          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef ENUM_KEYS_H
# define ENUM_KEYS_H

enum e_key {
	KEY_0,
	KEY_1,
	KEY_2,
	KEY_3,
	KEY_A,
	KEY_B,
	KEY_C,
	KEY_D,
	KEY_E,
	KEY_F,
	KEY_G,
	KEY_H,
	KEY_I,
	KEY_J,
	KEY_K,
	KEY_L,
	KEY_M,
	KEY_N,
	KEY_O,
	KEY_P,
	KEY_Q,
	KEY_R,
	KEY_S,
	KEY_T,
	KEY_U,
	KEY_V,
	KEY_W,
	KEY_X,
	KEY_Y,
	KEY_Z,
	KEY_30,
	KEY_31,
	KEY_32,
	KEY_33,
	KEY_34,
	KEY_35,
	KEY_36,
	KEY_37,
	KEY_38,
	KEY_39,
	KEY_40,
	KEY_ESC,
	KEY_BACKSPACE,
	KEY_43,
	KEY_44,
	KEY_45,
	KEY_46,
	KEY_47,
	KEY_48,
	KEY_49,
	KEY_50,
	KEY_51,
	KEY_52,
	KEY_53,
	KEY_54,
	KEY_55,
	KEY_56,
	KEY_57,
	KEY_58,
	KEY_59,
	KEY_60,
	KEY_61,
	KEY_62,
	KEY_63,
	KEY_64,
	KEY_65,
	KEY_66,
	KEY_67,
	KEY_68,
	KEY_69,
	KEY_70,
	KEY_71,
	KEY_72,
	KEY_73,
	KEY_74,
	KEY_75,
	KEY_76,
	KEY_77,
	KEY_78,
	KEY_RIGHT,
	KEY_LEFT,
	KEY_DOWN,
	KEY_UP,
	KEY_83,
	KEY_84,
	KEY_85,
	KEY_86,
	KEY_87,
	KEY_88,
	KEY_NB1,
	KEY_NB2,
	KEY_NB3,
	KEY_NB4,
	KEY_NB5,
	KEY_NB6,
	KEY_NB7,
	KEY_NB8,
	KEY_NB9,
	KEY_NB0,
};

#endif